name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - uses: lukka/get-cmake@latest
    - name: build
      run: mkdir build && cd build && cmake .. && make
